/*
 * This source file was generated by the Gradle 'init' task
 */
package aoc2024.d01 

import java.io.InputStream

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    companion object {
        fun solve(filename: String, expected: Int, solve: (InputStream) -> Int) {
            object {}.javaClass.getResourceAsStream(filename)?.use { stream ->
                val actual = solve(stream)
                println("File: $filename, Expected: $expected, Actual: $actual")
                assertEquals(expected, actual, "Expected value: $expected but got: $actual") 
            } ?: throw IllegalArgumentException("File not found: $filename")
        } 
    }

    class Part1 {
        @Test fun example() {
            solve("/d01/example.txt", 11, App()::solve)
        }

        @Test fun input() {
            solve("/d01/input.txt", 2970687, App()::solve)
        }
    }

    class Part2 {
        @Test fun example2() {
            solve("/d01/example.txt", 31, App()::solve2)
        }

        // @Test fun input2() {
        //     solve("/d01/input.txt", 23963899, App()::solve2)
        // }
    }
}